export let dataOfLang = {
    ru : {
        aboutUslangP : 'Кардинально сменить профессию и начать новую карьерную жизнь с первого листа - не самая простая задача. Такое резкое изменение можно сравнить с первой попыткой плаванья: это фантастика, потому что ничего не можешь предвидеть Различные курсы LevelUp являются одним из самых быстрых и простых шагов в начале ИТ-карьеры, который подойдет как гуманитариям, так и нетехническим специалистам)) Да да и даже тебе Курс включает в себя изучение основных типов тестирования, потом еще практическую работу над реальным проектом в конце обучения, изучение баз данных и все это с помощью наставника-профессионала, который уже успешно получил большой опыт работал с профессиональными разработчиками под большим и успешным проектов , Вы считаете себя гуманистом, но мечтаете ли вы о карьере в ИТ? Ознакомьтесь с нашими программами и присоединяйтесь!',

        aboutUslangP2 : `Вы мечтаете создать свое собственное веб-приложение и мобильное приложение? Тогда вам нужно выбрать LevelUp! С нашими курсами вы можете достичь своих целей и преодолеть все трудности, так как ничего невозможного с LevelUp , В течение 4х месячного курса ИТ вы узнаете базу и синтаксис кодирования, стандарты разработки и технологии, напишите свой веб-сайт, который вы придадите портфолио и будете всегда горды достижением ! Вы хотите доверять нам и владеть самыми популярными языками программирования с самого начала? Не теряя ни минуты следуйте программам учебных курсов! По окончанию сертификации LevelUp у вас будет возможность стать опытным разработчиком, спрос котго на ИТ-рынке будет расти по дням. LevelUp - это главный ключ к успеху:Мы гарантируем стабильные рабочие дни в неделю, регулярные рабочие часы в день, большой успех в работе, практика и конечно же опыт программирования в команде и работа с реальными проектами!`
    },

    en : {
        aboutUslangP  : 'Changing the profession and start a new life is not an easy job to do . Such changes can be compared with the first attempt to learn how to swim: it\'s fantastic, because nobody know what will happen The LevelUp\'s various courses are one of the fastest and easiest start of the IT career, which will suit both the humanitarians and non-technical specialists. The course includes learning the main types of testing, practicing on a real project at the end of training, studying databases, and all this with a mentor-professional who has already successfully gained a big experience And have worked with Professional developers under big and successful projects . You consider yourself a humanist, but do you dream about a career in IT? Check out our programs and join!',
        aboutUslangP2 : `Are you dreaming of creating your own Web and mobile application ? Then you Have to choose LevelUp ! With our courses you can reach your goals and overcome every difficulty , as nothing impossible with LevelUp . For 4 months of the IT course, you will learn the syntax of coding , the development frameworks and technologies, write your website , which you will attach to the portfolio and be proud of! Do you want to trust us and master the most popular programming languages from the early basis? Then follow the training course programs! After LevelUp certification you will have the opportunity become an experienced developer, the demand for who in the IT market will grow day by day . LevelUp is the main key to success: Stable working days per week , regular working hours a day, big job success score, practice and success again, experience in team programming and working with real projects!`


    },

    am : {
        aboutUslangP : 'Փոփոոխությունները միշտ էլ գովելի են ։ Առավել ևս երբ որոշում ես կայացնում փոխել մասնագիտությունը և ուժերը փորձել ժամանակակից ամենապահանջված մասնագիտության ՝ ծրագրավորման ոլորտում։ Level Up IT Center-ը հարմար և մատչելի հարթակ է՝ սկսելու ծանոթանալ ծրագրավորման հիմունքներին , ապա նաև դառնալ փորձառու մասնագետ։ Հ․Գ. Ծրագրավորման դասերը հասանելի են և հումանիտարների և ոչ տեխնիկական ուսում ստացաների համար։ Դուք ևս կարող եք դիմել եթե ձգտող եք և երազում եք ՏՏ-ում կարիերայի մասին՝ ապա առանց հապաղելու միացեք մեր թիմին ։ Ծրագրավոման կուրսերի ընթացքում կծանոթանաք ծրագրավորման հիմունքներին , կունենաք հնարավորություն աշխատելու իրական պրոյեկտի վրա ոլորտի լավագույն ներկայացուցիչների հետ ։',
        aboutUslangP2 : 'Մեր կողմից ընտրված ուսանողներին կդրդենք արդյունավետորեն կիրառելու ձեռք բերված հմտությունները: Մենք մշտապես բարելավում ենք ուսուցողական ծրագրերը `շուկայի պահանջներին համապատասխան: Մենք ընտրում ենք ոլորտի լավագույն մասնագետներին ովքեր հաջողությամբ կարող են Ձեզ փոխանցել իրենց գիտելիքներն ու հմտությունները: Մենք օգնում ենք շրջանավարտներին գտնել իրենց աշխատանքի լավագույն վայրը, իսկ գործատուներին կօգնենք որակյալ անձնակազմ գտնել: Հաճելի մթնոլորտն ու բարձր արդյունավետությունն ապահովված են:'
    }
}